language: java
jdk:
  - openjdk8
install:
  - mvn --settings .travis/settings.xml install -Dmaven.javadoc.skip=true -B -V
before_install:
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
deploy:
  -
    provider: script
    script: .travis/deploy.sh
    on:
      repo: com.lyra.payzensdk/payzen-ws-sdk
      branch: master
      jdk: openjdk8